function completionTimes = getLastCompletionTime()

lastCompletionTimesQuery = ...
"WITH last_session AS (SELECT max(id) as id, beginAt, finishAt, complexity" + newline + ...
"                      FROM session" + newline + ...
"                      GROUP BY complexity" + newline + ...
"                      ORDER BY complexity ASC)" + newline + ...
"SELECT min(r.task_duration) as time, ls.beginAt, ls.complexity as size, r.mistakes" + newline + ...
"FROM result r" + newline + ...
"         INNER JOIN last_session ls on ls.id = r.session_id" + newline + ...
"WHERE r.session_id IN (SELECT id FROM last_session)" + newline + ...
"GROUP BY r.session_id" + newline + ...
"ORDER BY ls.complexity ASC;";

results = database.fetchData(lastCompletionTimesQuery);

if isempty(results)
    completionTimes = model.CompletionTime(NaN, NaN, NaT);
else
    for k = height(results):-1:1
        completionTimes(k) = model.CompletionTime( ...
            results{k,'size'}, ...
            results{k, 'time'}, ...
            datetime(results{k, 'beginAt'}, 'ConvertFrom', 'posixtime'), ...
            results{k, 'mistakes'});
    end
end

end

