function sessions = getSessionsInfo(limit)
if nargin == 0
    limit = 500;
end

lastSessionsQuery = ...
"SELECT s.id, s.beginAt, s.finishAt, s.complexity || 'x' || s.complexity as size, min(r.task_duration) as min, max(r.task_duration) as max" + newline + ...
" FROM session s" + newline + ...
"          JOIN result r ON r.session_id = s.id" + newline + ...
"GROUP BY r.session_id" + newline + ...
"ORDER BY s.id DESC" + newline + ...
"LIMIT %d;";

query = sprintf(lastSessionsQuery, limit);
results = database.fetchData(query);

if isempty(results)
    sessions = model.SessionInfo(NaN, NaT, NaT, NaN, NaN);
else
    for k = height(results):-1:1
        sessions(k) = model.SessionInfo( ...
            results{k, 'id'}, ...
            datetime(results{k, 'beginAt'}, 'ConvertFrom', 'posixtime'), ...
            datetime(results{k, 'finishAt'}, 'ConvertFrom', 'posixtime'), ...
            results{k, 'size'}, ...
            results{k, 'min'}, ...
            results{k, 'max'});
    end
end

mustBeA(sessions, "model.SessionInfo");
end
